name: Get Group IDs to JSON

on:
  schedule:
    - cron: '0 6 * * *' # Runs every day at 06:00

  workflow_dispatch: # Allows manual trigger

env:
  UEK_LOGIN: ${{ secrets.UEK_LOGIN }}
  UEK_PASSWORD: ${{ secrets.UEK_PASSWORD }}

jobs:
  update-group-ids:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Use the latest Python 3.x version

      - name: Install required Python packages
        run: |
          pip install -r requirements.txt

      - name: Run the script to generate group_folder.json
        run: |
          python get_group_ids.py

      - name: Commit and push the updated .json file
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git pull
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update Group IDs"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          # Set this environment variable to push changes back to the repository
          # GITHUB_TOKEN is automatically provided by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
